# Usa l'immagine ROS Humble ottimizzata per Jetson (L4T)
FROM dustynv/ros:humble-desktop-l4t-r36.4.0

# use bash
SHELL ["/bin/bash", "-c"]

# update apt repository and upgrade existing ROS packages
RUN apt-get update || true && \
    apt-get install -y curl && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | apt-key add - && \
    apt-get update && \
    apt-get install --only-upgrade -y ros-humble-*

WORKDIR /root/deps_ws
RUN source /opt/ros/humble/install/setup.bash && \
    mkdir -p src && \
    git clone https://github.com/ros/bond_core.git --branch ros2 ./src/bond_core && \
    git clone https://github.com/ros/diagnostics.git --branch ros2-humble ./src/diagnostics && \
    git clone https://github.com/BehaviorTree/BehaviorTree.CPP.git --branch v3.8 ./src/behaviortree_cpp_v3 && \
    colcon build --symlink-install --parallel-workers 1 --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wl,--no-keep-memory"
    
# Set the working directory to your workspace
WORKDIR /root/nav2_ws

# Workaround for converting tf_utils (required for building nav2)
RUN mkdir -p /opt/ros/humble/install/include/tf2/tf2 && \
    echo '#include "tf2/utils.h"' > /opt/ros/humble/install/include/tf2/tf2/utils.hpp

# clone and build nav2
RUN source /opt/ros/humble/install/setup.bash && \
    source /root/deps_ws/install/setup.bash && \
    mkdir -p src && \
    git clone https://github.com/ros-navigation/navigation2.git --branch humble ./src/navigation2 && \
    rosdep install -y \
      --from-paths src \
      --ignore-src \
      --skip-keys "gazebo_ros_pkgs" && \
    colcon build \
      --symlink-install \
      --parallel-workers 1 \
      --packages-ignore nav2_system_tests \
      --cmake-args \
        -DCMAKE_BUILD_PARALLEL_LEVEL=1 \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_CXX_FLAGS="-Wl,--no-keep-memory" \
        -DBUILD_TESTING=OFF \
        -DAMENT_CMAKE_ENABLE_TESTING=OFF \
        -Dompl_DIR=/opt/ros/humble/share/ompl/cmake

# clone and install slam toolbox
RUN git clone https://github.com/SteveMacenski/slam_toolbox.git --branch humble ./src/navigation2/slam_toolbox

# Build the workspace
RUN source /opt/ros/humble/install/setup.bash && \ 
    colcon build \
      --packages-select slam_toolbox \
      --symlink-install \
      --parallel-workers 1 \
      --cmake-args -DCMAKE_BUILD_PARALLEL_LEVEL=1
      
# install additional packages
RUN apt-get update && \
    apt-get install -y ros-humble-rqt-tf-tree && \
    apt-get install -y iproute2 net-tools && \
    apt install -y libpcl-dev && \
    apt install -y cmake

# install livox-sdk2
RUN cd /root && \
    git clone https://github.com/Livox-SDK/Livox-SDK2.git && \
    cd ./Livox-SDK2/ && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j1 && \
    make install


# Aggiungi usr/local/lib to dynamic linker path (so livox-sdk2 is visible to any other program)
RUN echo "/usr/local/lib" > /etc/ld.so.conf.d/usr-local-lib.conf && ldconfig

# Copia il file init.bash locale nel container (nella cartella temporanea)
COPY app/initialize/init_ARM.bash /tmp/init_ARM.bash

# Aggiungi il contenuto di init.bash in coda al .bashrc di root e rimuovi il file temporaneo
RUN cat /tmp/init_ARM.bash >> /root/.bashrc && \
    rm /tmp/init_ARM.bash

# remove cache data of APT metadata     
RUN rm -rf /var/lib/apt/lists/*

